version: "3.8"

services:
  backend:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend-service

  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    container_name: manager-frontend
    depends_on:
      - backend

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    container_name: dashboard-frontend
    depends_on:
      - backend
