DROP TABLE IF EXISTS AWESOME_TOILET.alarmdata;
DROP TABLE IF EXISTS AWESOME_TOILET.environmentdata;
DROP TABLE IF EXISTS AWESOME_TOILET.message;
DROP TABLE IF EXISTS AWESOME_TOILET.toiletstatus;
DROP TABLE IF EXISTS AWESOME_TOILET.trafficdata;
DROP TABLE IF EXISTS AWESOME_TOILET.toilet;