DROP TABLE IF EXISTS AWESOME_TOILET.alarmdata;
DROP TABLE IF EXISTS AWESOME_TOILET.environmentdata;
DROP TABLE IF EXISTS AWESOME_TOILET.reviews;
DROP TABLE IF EXISTS AWESOME_TOILET.toiletstatus;
DROP TABLE IF EXISTS AWESOME_TOILET.trafficdata;
